In [1]:
import numpy as np
import pandas as pd

In [2]:
train_df= pd.read_csv('train.csv')
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150096 entries, 0 to 150095
Data columns (total 3 columns):
 #   Column      Non-Null Count   Dtype 
---  ------      --------------   ----- 
 0   Unnamed: 0  150096 non-null  int64 
 1   Text        150096 non-null  object
 2   Category    150096 non-null  object
dtypes: int64(1), object(2)
memory usage: 3.4+ MB


In [3]:
data=pd.read_csv('rawcategories.csv',header=None)

In [45]:
data[data[0]=='Natural Environment']

0
558     Natural Environment
805     Natural Environment
1039    Natural Environment
1249    Natural Environment
1350    Natural Environment
...                     ...
149650  Natural Environment
149658  Natural Environment
149718  Natural Environment
149733  Natural Environment
150022  Natural Environment

[851 rows x 1 columns]

In [6]:
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize

ps = PorterStemmer()

In [66]:
topic_cluster_mapping = {
    "economic": [
        'Economy',
        'Economy.Bank and Bourse',
        'Economy.Oil',
        'Economy.Commerce',
        'Economy.Industry',
        'Economy.Agriculture',
        'Economy.Dwelling and Construction'
    ],
    "cultural and artistic": [
        'Science and Culture',
        'Science and Culture.Science.Book',
        'Literature and Art',
        'Literature and Art.Art',
        'Literature and Art.Art.Cinema',
        'Literature and Art.Art.Music',
        'Literature and Art.Art.Theater',
        'Science and Culture.Science',
        'Science and Culture.Science.Medicine and Remedy',
        'Literature and Art.Literature'
    ],
    "political": [
        'Politics',
        'Politics.Iran Politics'
    ],
    "technological": [
        'Science and Culture.Science.Information and Communication Technology'
    ],
    "sports": [
        'Sport',
        'Sport.World Cup'
    ],
    "social": [
        'Social',
        'Social.Women',
        'Social.Religion'
    ],
    "miscellaneous": [
        'Miscellaneous',
        'Miscellaneous.World News',
        'Miscellaneous.Urban',
        'Miscellaneous.Picture',
        'Miscellaneous.Happenings',
        'Miscellaneous.Islamic Councils',
        'Miscellaneous.Picture.Caricature'
    ],
    "tourism": [
        'Tourism'
    ],
    "environment": [
        'Natural Environment'
    ]
}

def categoesMapping(cat):
    for key,value in topic_cluster_mapping.items():
        if cat in value:
            return key

In [67]:
categiesdData=train_df['Category'].apply(categoesMapping)


In [73]:
train_df['Category'].shape

(150096,)

In [71]:
from sklearn import preprocessing 
  
# label_encoder object knows  
# how to understand word labels. 
label_encoder = preprocessing.LabelEncoder() 
  
# Encode labels in column 'species'. 
categiesdData= label_encoder.fit_transform(categiesdData) 
  


array([0, 6, 1, ..., 3, 0, 4])

In [77]:
pd.DataFrame(categiesdData, columns=['Category'],index=None).to_csv('categoriesData.csv',index=None)

In [16]:
stemList=[]
for x in list(category_keywords.keys()):
    stemList.append(ps.stem(x))
stemList

['econom',
 'cultural and artist',
 'polit',
 'technolog',
 'sport',
 'social',
 'miscellan',
 'tourism',
 'natural environ']

In [23]:
from nltk.stem import WordNetLemmatizer
import re
X = train_df['Category']
documents = []


stemmer = WordNetLemmatizer()

for sen in range(0, len(X)):
    # Remove all the special characters
    document = re.sub(r'\W', ' ', str(X[sen]))
    
    # remove all single characters
    document = re.sub(r'\s+[a-zA-Z]\s+', ' ', document)
    
    # Remove single characters from the start
    document = re.sub(r'\^[a-zA-Z]\s+', ' ', document) 
    
    # Substituting multiple spaces with single space
    document = re.sub(r'\s+', ' ', document, flags=re.I)
    
    # Removing prefixed 'b'
    document = re.sub(r'^b\s+', '', document)
    
    # Converting to Lowercase
    document = document.lower()
    
    # Lemmatization
    document = document.split()

    document = [stemmer.lemmatize(word) for word in document]
    document = ' '.join(document)
    
    documents.append(document)

In [25]:
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(max_features=1500, min_df=5, max_df=0.7, stop_words=stopwords.words('english'))
X = vectorizer.fit_transform(documents).toarray()

In [26]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidfconverter = TfidfTransformer()
X = tfidfconverter.fit_transform(X).toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [16]:
# import re
import difflib
def categories (category):
    # regex1= r'cultur(e|al)'
    # regex2 = r'(art)(ist)*'

    result=difflib.get_close_matches(category,candidate_labels)
    if len(result)>0:
        return result[0]
    return 'miscellaneous'


In [26]:
train_df['Category'][:15]

0          Science and Culture
1                        Sport
2                      Economy
3     Miscellaneous.World News
4                        Sport
5          Miscellaneous.Urban
6                        Sport
7                 Social.Women
8                       Social
9     Miscellaneous.World News
10          Literature and Art
11                    Politics
12         Science and Culture
13               Miscellaneous
14                      Social
Name: Category, dtype: object

In [ ]:
categoriesdData = train_df['Category'].apply(categories)


In [78]:
categiesdData

array([0, 6, 1, ..., 3, 0, 4])

In [ ]:
data.to_csv('classifiedCategories.csv',header=None,index=None)

In [16]:
Y_train=train_df['Category']

In [116]:
from sklearn.model_selection import train_test_split
X_train , x_test ,y_train ,y_test = train_test_split(train_df['Text'],categiesdData,test_size=0.3,random_state=42)

In [185]:
import re
def remove_urls(text):
    url_pattern = re.compile(r'https?://\S+')
    return url_pattern.sub('', text)
def preProcessText(x:str):
    x = remove_urls(x)
    x = re.sub(r'[^\w\s]','',x)
    x = re.sub(r'\d', '', x)
    
    # remove all single characters
    x = re.sub(r'\s+[a-zA-Z]\s+', '', x)
    
    # Remove single characters from the start
    x = re.sub(r'\^[a-zA-Z]\s+', '', x) 

    x = re.sub(r'\n', '', x) 
    
    stopWordsFile = open('./stopwords.dat')
    stopWordsFile2 = open('./persian-stopwords/persian')
    combined=stopWordsFile.read().split('\n') + stopWordsFile2.read().split('\n')
    stopWords= set(combined)
    if 'برای' in stopWords:
        print('wtf')
    splitedText = [word for word in x.split(' ') ]
    print(splitedText)
    result=[]
    for word in splitedText:
        if word not in stopWords:
            result.append(word)
    return ' '.join(result)


In [186]:
preProcessText(X_train.iloc[0])

wtf
['نمايش', 'ويژه', 'زماني', 'براي', 'مستي', 'اسبها', 'فيلم', 'زماني', 'براي', 'مستي', 'اسبها', 'براي', 'روزنامه', 'نگاران', 'و', 'خانواده', 'هاي', 'آنان', 'نمايش', 'داده', 'مي', 'شود', 'اين', 'فيلم', 'دوشنبه', '', 'دي', '', 'ساعت', 'در', 'سينما', 'سپيده', 'براي', 'اعضاي', 'انجمن', 'صنفي', 'روزنامه', 'نگاران', 'و', 'خانواده', 'آنان', 'به', 'نمايش', 'درمي', 'آيد', 'اعضاي', 'متقاضي', 'مي', 'توانند', 'جهت', 'رزرو', 'بليت', 'با', 'شماره', 'هاي', '', '', '', 'و', 'تماس', 'حاصل', 'كنند', 'گفتني', 'است', 'فيلم', 'زماني', 'براي', 'مستي', 'اسبها', 'به', 'كارگرداني', 'بهمن', 'قبادي', 'برنده', 'دوربين', 'طلايي', 'جشنواره', 'كن', 'امسال', 'بوده', 'است', '']


'نمايش ويژه زماني براي مستي اسبها فيلم زماني براي مستي اسبها براي روزنامه نگاران خانواده هاي نمايش مي اين فيلم دوشنبه دي ساعت سينما سپيده براي اعضاي انجمن صنفي روزنامه نگاران خانواده نمايش درمي آيد اعضاي متقاضي مي رزرو بليت شماره هاي تماس حاصل كنند گفتني فيلم زماني براي مستي اسبها كارگرداني بهمن قبادي برنده دوربين طلايي جشنواره كن'

In [10]:
from hazm import word_tokenize
# converting each sentence to list of words and inserting in sents
X_train = X_train.apply(word_tokenize)

In [11]:
X_train

0       [خبرنامه, دانشگاه, علم, صنعت, ايران, شماره, يا...
1       [پايان, سال, دهها, زمين, فوتبال, سالن, ورزش, ب...
2       [انجمن, توليدكنندگان, تجهيزات, صنعت, نفت, تشكي...
3       [كرتين, براي, سومين, وزير, كانادا, ژان, كرتين,...
4       [رفقا, نمايندگان, اروپاي, شرقي, جام, بابك, كما...
                              ...                        
9995    [مسئوليت, شهروندان, رئيس, جمهور, راي, خويش, تي...
9996    [مديرمسئول, روزنامه, همبستگي, دادگاه, احضار, گ...
9997    [شيرهاي, آب, توجه, موقعيت, بحراني, ذخاير, آب, ...
9998    [نيم, رخ, نگاهي, زندگي, جبران, خليل, جبران, پس...
9999    [پيروزي, پيكان, مدعي, واليبال, برتر, باشگاههاي...
Name: Text, Length: 10000, dtype: object

In [12]:
from gensim.models import Word2Vec

w2v_model = Word2Vec(sentences=X_train, vector_size=50, window=5,seed=42, min_count=10, workers=4)

In [144]:
w2v_model.wv.most_similar('اقتصاد',topn=10)

[('ليگ', 0.9693446755409241),
 ('باشگاهي', 0.9688852429389954),
 ('بازيهاي', 0.9644466042518616),
 ('قهرماني', 0.9510931372642517),
 ('تيمهاي', 0.9510273337364197),
 ('تيمي', 0.9507378339767456),
 ('رقابتهاي', 0.9420532584190369),
 ('برتر', 0.9419983625411987),
 ('بازيكنانش', 0.9363963007926941),
 ('گيران', 0.9300103187561035)]

In [13]:
def vectorize(sentence):
    words = sentence.split()
    words_vecs = [w2v_model.wv[word] for word in words if word in w2v_model.wv]
    if len(words_vecs) == 0:
        return np.zeros(100)
    words_vecs = np.array(words_vecs)
    return words_vecs.mean(axis=0)

In [14]:
X_train = np.array([vectorize(sentence) for sentence in X_train])
